# Generated by Django 4.2.3 on 2023-07-10 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrato', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valores',
            options={'verbose_name': 'Valores', 'verbose_name_plural': 'Valores'},
        ),
    ]
