# Generated by Django 4.2.3 on 2023-07-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_categoria_categoria_categoria_essencial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=50)),
                ('Banco', models.CharField(choices=[('NU', 'Nubank'), ('CE', 'Caixa Econômica'), ('BD', 'Bradesco'), ('IT', 'Itaú')], max_length=2)),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2)),
                ('icone', models.ImageField(upload_to='icones')),
            ],
        ),
    ]
