# Generated by Django 4.2.3 on 2023-07-03 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_conta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta',
            old_name='Banco',
            new_name='banco',
        ),
    ]
