# Generated by Django 4.2.3 on 2023-07-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_rename_banco_conta_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='valor',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='conta',
            name='banco',
            field=models.CharField(choices=[('NU', 'Nubank'), ('CE', 'Caixa Econômica'), ('BD', 'Bradesco'), ('BD', 'Bradesco'), ('IT', 'Itaú')], max_length=2),
        ),
    ]
