# Generated by Django 4.2.3 on 2023-07-10 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contapagar',
            old_name='categoria',
            new_name='categoria_id',
        ),
    ]
